title: Kwesi Twentwewa Quagraine
logo: Assets/Kwesi_headshot.jpg
description: Kwesi T. Quagraine is a Ph. D. Candidate at the Earth and Atmospheric Science Department in Indiana University - Bloomington, Indiana. Kwesi has a passion for weather and climate extremes, their variability and impacts on living things. Kwesi couples as a climate data scientist and has extensive experience on analysing huge datasets using parallel computing on HPC systems.
show_downloads: true
theme: jekyll-theme-minimal
